### ISSUE TITLE
Email/Phone fields support

### ISSUE THREAD

**Issue by gurify** [podio/podio-dotnet#12]
Are the newly introduced Email/Phone fields already supported in the API?

**Comment by AjmalVh** [comment]
No. We will add support for Email/Phone field this week.

**Comment by AjmalVh** [comment]
Added support for Email and Phone fields: https://github.com/podio/podio-dotnet/commit/efd53cad3efccb69fec51f1a3358b4498c535336

See the examples here: http://podio.github.io/podio-dotnet/fields/
