### ISSUE TITLE
Bad Request Exception when updating textfield of an item.

### ISSUE THREAD

**Issue by agarcia00** [podio/podio-dotnet#15]
Get error when trying to add a value to a text field within the item. 

PodioAPI.Models.Item AppItem = podio.ItemService.GetItemBasic(item);
        var user = AppItem.Field<TextItemField>("title");
        var folder = AppItem.Field<TextItemField>("share-folder-name");
        var mgrField = AppItem.Field<TextItemField>("manager-email");
      mgrField.Value = mgr;
      podio.ItemService.UpdateItem(AppItem); //Get Bad Request Exception

**Comment by AjmalVh** [comment]
Hi @agarcia00 

The item update wont work this way. You need to create a new Item object and update the values. See the documentation here: http://podio.github.io/podio-dotnet/items/
