### ISSUE TITLE
Filtering not supported for fields of type email

### ISSUE THREAD

**Issue by gurify** [podio/podio-dotnet#16]
When trying to search for items using the new Email field, PodioBadRequestException is thrown with this message:
"Filtering not supported for fields of type email".
How can we filter the items in the meanwhile?

**Comment by AjmalVh** [comment]
Filtering by an Email field is not supported by Podio API. You can use [Search in app](https://developers.podio.com/doc/search/search-in-app-4234651) API to achieve the same.

**Comment by gurify** [comment]
Is there a way to search by the exact email? When I use App search with email 'someone@gmail.com' it returns all the items that have 'gmail.com' and even '.com'

**Comment by AjmalVh** [comment]
I have also gone through the same situation. There is no way to restrict to exact matches in Podio search API.
