### ISSUE TITLE
ApplicationService.GetApp returns empty app token

### ISSUE THREAD

**Issue by gurify** [podio/podio-dotnet#17]
The app token returned by the ApplicationService.GetApp method is null.

Pseudo code:
Application newApp = new Application
            {
                SpaceId = request.WorkspaceId,
                Config = masterApplication.Config,
                Fields = activeFields
            };

int installedAppId = podioClient.ApplicationService.AddNewApp(newApp);

Application newlyCreatedApp = podioClient.ApplicationService.GetApp(installedAppId);
newlyCreatedApp.Token is null

**Comment by AjmalVh** [comment]
@gurify 
Is the Token null only if the app is created via API ?

**Comment by gurify** [comment]
Seems that way. Does not reproduce on sandbox

**Comment by AjmalVh** [comment]
@gurify 

Podio is not returning the token when GetApp is called via API. I confirmed this by inspecting the response JSON. 
![2015-10-19_11-10-02](https://cloud.githubusercontent.com/assets/1432316/10570536/94d0c5c0-7652-11e5-9e95-9d19eaa73174.png)

**Comment by AjmalVh** [comment]
Hi @gurify 

I have talked with Podio team and found you need to have an increased trust level to retrieve the app token via the API. 

Please send a request to support@podio.com for this. They will review your request and may provide an increased trust level.
