### ISSUE TITLE
Trying to get a contact email returns 404 error

### ISSUE THREAD

**Issue by apttie** [podio/podio-dotnet#18]
Trying something like this:

try:
int[] profileID = { Convert.ToInt32(itemCurrent.CreatedBy.Id)};
List<Contact> profileList = podio.ContactService.GetContactsByProfileId(profileID);

throws: 
PodioAPI.Exceptions.PodioNotFoundException' was thrown.
404
not_found
Object not found

Is this a trust issue?

**Comment by AjmalVh** [comment]
@apttie 

That is because `itemCurrent.CreatedBy.Id` returns the `user_id`, not the `profile_id`. You need profile_id(s) to as the argument for GetContactsByProfileId. You can get the profile_id of a user, using this API call: https://developers.podio.com/doc/contacts/get-user-contact-60514
