### ISSUE TITLE
PodioException is not serializble

### ISSUE THREAD

**Issue by cluedindev** [podio/podio-dotnet#19]
Hi.

Can you please mark the PodioException as Serizliable?

It will help us fix this issue with using the library:

System.Runtime.Serialization.SerializationException: Type 'PodioAPI.Exceptions.P
odioNotFoundException' in Assembly 'Podio.NET, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null' is not marked as serializable.
Server stack trace:
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSeriali
ze(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, S
erObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter
objectWriter, SerializationBinder binder)
at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(O
bject obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerOb
jectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter obje
ctWriter, SerializationBinder binder)
at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Obje
ct graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(S
tream serializationStream, Object graph, Header[] headers, Boolean fCheck)
at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage..ctor(IMethodC
allMessage mcm)
at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMe
ssage reqMsg)

Thanks,

- Tim

**Comment by AjmalVh** [comment]
Hi @cluedindev 

I have updated the code. Please get the latest package from Nuget

**Comment by cluedindev** [comment]
Thanks! It works.

[CluedIn]<http://cluedin.io>

Tim  / Chief Clue Officer
tiw@cluedin.io<mailto:tiw@cluedin.io> / +45 53 84 15 16

CluedIn
+(45) 65 71 14 04
https://www.cluedin.n<http://cluedin.io>et

On 26 Jan 2016, at 12:52 pm, Ajmal vh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @cluedindev<https://github.com/cluedindev>

I have updated the code. Please get the latest package from Nuget
