### ISSUE TITLE
Serialization Issue calling GetTagsOnApp

### ISSUE THREAD

**Issue by cluedindev** [podio/podio-dotnet#24]
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 
  Module "PodioAPI.Services.TagService", line 68, col 0, in GetTagsOnApp
    System.Collections.Generic.List`1[PodioAPI.Models.Tag] GetTagsOnApp(Int32, System.Nullable`1[System.Int32], System.String)
  Module "PodioAPI.Podio", line 200, col 0, in Get
    T Get[T](System.String, System.Collections.Generic.Dictionary`2[System.String,System.String], System.Object)
  Module "PodioAPI.Podio", line 8453, col 0, in Request
    T Request[T](PodioAPI.RequestMethod, System.String, System.Object, System.Object)
  Module "System.Dynamic.UpdateDelegates", line 277, col 0, in UpdateAndExecute2
    TRet UpdateAndExecute2[T0,T1,TRet](System.Runtime.CompilerServices.CallSite, T0, T1)
  Module "Newtonsoft.Json.JsonConvert", line 11, col 0, in DeserializeObject
    T DeserializeObject[T](System.String, Newtonsoft.Json.JsonConverter[])
  Module "Newtonsoft.Json.JsonConvert", line 54, col 0, in DeserializeObject
    System.Object DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings)
  Module "Newtonsoft.Json.JsonSerializer", line 83, col 0, in DeserializeInternal
    System.Object DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
  Module "Newtonsoft.Json.Serialization.JsonSerializerInternalReader", line 219, col 0, in Deserialize
    System.Object Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
  Module "Newtonsoft.Json.Serialization.JsonSerializerInternalReader", line 73, col 0, in ReadForType
    Boolean ReadForType(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonContract, Boolean)
  Module "Newtonsoft.Json.JsonReader", line 0, col 0, in ReadAndMoveToContent
    Boolean ReadAndMoveToContent()
  Module "Newtonsoft.Json.JsonTextReader", line 82, col 0, in Read
    Boolean Read()
  Module "Newtonsoft.Json.JsonTextReader", line 0, col 0, in ParseValue
    Boolean ParseValue()

**Comment by AjmalVh** [comment]
Working for me. You can [debug using Fiddler proxy](http://www.telerik.com/fiddler) and see what is happening in your case.
![tag](https://cloud.githubusercontent.com/assets/1432316/16555376/f7a044da-41f1-11e6-9b94-69e59ff0a9b5.jpg)
