### ISSUE TITLE
GetReferencesToItemByField not returning result

### ISSUE THREAD

**Issue by matq007** [podio/podio-dotnet#25]
Hi I am trying to access item with GetReferencesToItemByField, but I am getting no result. Can you check it out?

**Comment by AjmalVh** [comment]
The method is working perfect. It will retrieve all items, referenced from a particular field, when supplied with item_id of the referenced item and field_id of field which it is referenced from. 

For example, if you have a Project and Timesheet App. Your Timesheet App got a relationship field named 'Working project' that can reference a project item. If you supply the field_id of  'Working project' field of timesheet app and item_id of a particular project, it will return all the projects referenced from the 'Working project' field of timesheet app. Hope it makes sense.

![capture](https://cloud.githubusercontent.com/assets/1432316/17543255/e246fcec-5eec-11e6-945e-f733269ef4c4.JPG)
