### ISSUE TITLE
Unhandled Json parse errors

### ISSUE THREAD

**Issue by olegivo** [podio/podio-dotnet#26]
Sometimes Podio server responses in not-json-like format, that cause deserialization exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
All PodioExceptions are handled, but json deserialization exception cause fatal application error.

**Comment by olegivo** [comment]
Probably it happens because some fields can contain string with html tags.
But inpossible to know the value that cause exception.

**Comment by AjmalVh** [comment]
I have also experienced similar issue randomly. Sometimes, Podio API return something other than JSON. It is not because of the field contains HTML tags. But I was not able reproduce the issue. We can throw a 'PodioException' but not yet sure what is the root cause.

**Comment by olegivo** [comment]
For example of not-json podio response I found [this on Podio Forums](https://help.podio.com/hc/en-us/community/posts/200517258--Bad-Request-Error).
>`<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor="white">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n`

Maybe when Podio responses is not-json-like we need to throw custom PodioException with available response content for further analysis?

**Comment by AjmalVh** [comment]
Yes, we can do that I guess. Ideally Podio should sent a JSON with 400 status code in case of bad request.

**Comment by AjmalVh** [comment]
This issue is handled in this PR: https://github.com/podio/podio-dotnet/pull/52
It will throw an PodioInvalidJsonException
