### ISSUE TITLE
ItemRevision Model's ItemRevisionId fields needs to be an int

### ISSUE THREAD

**Issue by martenataalla** [podio/podio-dotnet#46]
ItemRevision.ItemRevisionId has reached numbers beyond what int can handle. Changing to a long seems to work. Can you please change? thanks

**Comment by martenataalla** [comment]
I've submitted an edit/patch for approval.

**Comment by PavloBasiuk** [comment]
Sorry, can't see your PR, so created new one https://github.com/podio/podio-dotnet/pull/47

**Comment by PavloBasiuk** [comment]
Fixed in https://github.com/podio/podio-dotnet/pull/47
