### ISSUE TITLE
MoneyItemField value not updating on item update

### ISSUE THREAD

**Issue by jshoey** [podio/podio-dotnet#8]
Updating a money field on an item doesn't update the value.  The value is set to $0 and does not reflect the value that it was supposed to be updated to.  Two fields should be updated, only the category field is updated and the money field isn't.

```
var updateItem = new PodioAPI.Models.Item();
var jobValueField = updateItem.Field<MoneyItemField>("job-value");
jobValueField.Currency = "AUD";
jobValueField.Value = 20.0000M;
var statusField = updateItem.Field<CategoryItemField>("job-status");
statusField.OptionId = 1; //Id comes from option mapping
updateItem.ItemId = podioJobsItem.ItemId; //Item Id comes from foreach
clientJobs.ItemService.UpdateItemFieldValues(updateItem) 
```

**Comment by AjmalVh** [comment]
Hi @jshoey 

That is not working because you are using UpdateItemFieldValues method in ItemService , which is used to update only one field (specifed in xml documentation for that method). Please use UpdateItemValues or UpdateItem method to update multiple fields in of an item.
