### ISSUE TITLE
ItemService.AddNewItem(AppId, newItem) does not fire webhook

### ISSUE THREAD

**Issue by gurify** [podio/podio-dotnet#9]
We have an item.create webhook registered. It fires ok when new item is added via email to app, but when item is added via the .net client it does not.
I've tried to explicitly set hook = true when calling AddNewItem, like this: ItemService.AddNewItem(AppId, newItem, false, true), but without any luck.
Any thoughts?

**Comment by AjmalVh** [comment]
https://help.podio.com/hc/communities/public/questions/203081327--NET-client-ItemService-AddNewItem-AppId-newItem-does-not-fire-webhook?page=1#answer-204575907
